// @flow
export const LOADING_PERMISSSION = "LOADING_PERMISSSION"
export const SET_LIST_ROLE = "SET_LIST_ROLE"
export const SET_DETAIL_ROLE = "SET_DETAIL_ROLE"
export const SET_INPUT_DETAIL = "SET_INPUT_DETAIL"
export const SET_PERMISSION_LIST = "SET_PERMISSION_LIST"
