---
- name: Checkout repository
  git:
    repo: "{{app_repo}}"
    dest: "{{app_root}}"
    force: true
    version: "{{app_rev}}"
    accept_hostkey: true

- name: Create config directory
  become: yes
  file:
    path: "{{ app_root }}/app/config"
    recurse: yes
    group: www-data
    mode: 0755
    owner: "{{username}}"
    state: directory

- name: Include config for environment "{{app_env}}"
  copy:
    content: "{{ lookup('env', 'CONFIGS_' + APP_ENV) }}"
    dest: "{{app_root}}/app/config/index.js"
    force: yes

- name: Create STATIC_ROOT directory
  become: yes
  file:
    path: "{{ lookup('env', 'STATIC_ROOT') }}"
    recurse: yes
    group: "www-data"
    mode: '0755'
    owner: "{{username}}"
    state: directory
